services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: souqmasr
      POSTGRES_PASSWORD: souqmasr_dev_pw
      POSTGRES_DB: souqmasr
    ports:
      - "5432:5432"
    volumes:
      - souqmasr_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - souqmasr_redis_data:/data

volumes:
  souqmasr_postgres_data:
  souqmasr_redis_data:
